[package]
name = "rosu-tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
rosu-v2 = { git = "https://github.com/MaxOhn/rosu-v2", branch = "lazer", features = ["serialize"] }
rosu-pp = { git = "https://github.com/MaxOhn/rosu-pp", branch = "main" }
tokio-tungstenite = "0.24.0"
tokio = { version = "1.41.1", features = ["rt-multi-thread"] }
serde = { version = "1.0.215" }
serde_json = "1.0.133"
hyper = "1.5.1"
dotenvy = "0.15.7"
toml = "0.8.19"
futures-util = "0.3.31"
hyper-util = {version = "0.1.10", features = ["tokio"]}

